name: set-default-matrix-dispatch

on:
  workflow_dispatch:

jobs:
  call-set-default-matrix:
    uses: ./.github/workflows/callable/set-default-matrix.yml

  echo-matrix:
    runs-on: ubuntu-latest
    needs: call-set-default-matrix
    steps:
      - name: Echo matrix output
        run: |
          echo "Matrix output from set-default-matrix workflow:"
          echo '${{ needs.call-set-default-matrix.outputs.matrix }}' | jq .
